stacks:
  test:
    subnet_allocation: 15


loadbalancers:
  -
    name: LocustMaster
    records:
      - locust
    idle_timeout: 120
    default_targetgroup:
      protocol: http
      healthcheck:
        port: 80
        protocol: http
        threshold_count: 3
    listeners:
      -
        name: http
        port: 80
        protocol: http
  -
    name: LocustSlaveNetwork
    records:
      - locustMaster
    type: network
    internal: true
    default_targetgroup:
      protocol: tcp
      healthcheck:
        protocol: tcp
        port: 5557
        threshold_count: 3
    listeners:
      -
        name: tcp
        port: 5557
        protocol: tcp

securityGroups:
  LocustMaster:
    -
      rules:
        -
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
        -
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443
      ips:
        - 0.0.0.0/0
  LocustSlaveNetwork:
    -
      rules:
        -
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
        -
          IpProtocol: tcp
          FromPort: 5557
          ToPort: 5558
      ips:
        - stack

targetgroups:
  locustmaster:
    loadbalancer: LocustMaster
    healthcheck:
      path: '/'
    listeners:
      - http
    conditions:
      - host: 'locust.*'
    priority: 12
  locustslave:
    loadbalancer: LocustSlaveNetwork
    healthcheck:
      protocol: tcp
      port: 5557
    protocol: tcp